namespace OCPI.Commands
{
    public enum CommandResult
    {
        ACCEPTED, CANCELLED_RESERVATION, EVSE_OCCUPIED, EVSE_INOPERATIVE, FAILED, NOT_SUPPORTED,
        REJECTED, TIMEOUT, UNKNOWN_RESERVATION
    }
}
