namespace OCPI.CDRs
{
    public enum CDRDimensionType
    {
        CURRENT, ENGERY, ENTERY_EXPORT, ENGERY_IMPORT, MAX_CURRENT, MIN_CURRENT, MAX_POWER, 
        MIN_POWER, PARKING_TIME, POWER, RESERVATION_TIME, STATE_OF_CHANGE, TIME
    }
}
